[theme]
base = "light"
primaryColor = "#4CAF50"  # Vale-Bay green
backgroundColor = "#F5F5F5"  # Soft gray
secondaryBackgroundColor = "#E8E8E8"  # Slightly darker gray
textColor = "#333333"  # Dark text for readability
font = "sans serif"